trigger:
- develop-git-ci

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: upgrade_rc_version
    displayName: 'Upgrade RC version'
    jobs:
      - job: upgrade_rc_version
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Install Node.js'
          - checkout: self
            persistCredentials: true
          - script:
              git checkout $(DEVELOP_BRANCH_NAME)
            displayName: 'Git Checkout'
          - script: 
              git config --global user.email "$(GIT_USER_MAIL)" && git config --global user.name "$(GIT_USER_NAME)"
          - script:
              npm version prerelease --preid=rc -m "upgrade version [ci skip]"
            displayName: 'Upgrade version'
          - script:
              git push
            displayName: 'Push upgraded version'
